version: '3'

services:
  # duckling
  duckling:
    image: rasa/duckling
    restart: always
    container_name: duckling
    ports: 
      - 8000:8000
# mqtt
  mqtt:
    image: syntithenai/hermod-python
    build: ./hermod-python/
    container_name: mqtt
    entrypoint: ['python','/app/src/services.py','-ss','-m','-r','default']
    #environment:
      # see volume mount below
      #SSL_CERTIFICATES_FOLDER: /app/certs
    ports:
      - 9001:9001
      # expose for logging
      - 1883:1883
    volumes:
      # mount certificates folder
      # - /etc/letsencrypt/live/peppertrees.asuscomm.com:/app/certs
      # dev mount src
      - ./hermod-python/src:/app/src 
      # share mosquitto files via host mount for password updates
      - ./hermod-python/mosquitto:/etc/mosquitto 
      
     
# hermod
  hermod:
    image: syntithenai/hermod-python
    build: ./hermod-python/
    container_name: hermod
    # to enable local audio, restore the following line and uncomment pulse environment variables and host mount
    #entrypoint: ['python','/app/src/services.py','-r','http://rasa:5005']
    entrypoint: ['python','/app/src/services.py','-r','http://rasa:5005','-nl']
    environment:
      RASA_URL: http://rasa:5005
      MQTT_SERVER: mqtt
      # defaults. to change, use mosquitto_password to edit hermod-python/mosquitto/password and mosquitto/acl
      # MQTT_PORT: hermod_server
      # MQTT_USER: hermod_server
      # MQTT_PASSWORD: hermod
      
      # BY DEFAULT LOCAL AUDIO IS DISABLED, SEE entrypoint, environment and volumes to enable
      # ENABLE PULSE AUDIO
      PULSE_HOST: ${PULSE_HOST}
      PULSE_COOKIE: /tmp/cookie
      
      # if pulse is not available, it is possible to set the sound devices directly
      # note that the microphone device needs to deliver 16K 1channel audio
      # MICROPHONE_DEVICE: dmix
      # SPEAKER_DEVICE: dmix
      
      # to enable google high quality ASR create and download service account credentials for a project with speech to text enabled
      #GOOGLE_APPLICATION_CREDENTIALS: /app/src/google-asr-credentials.json
      #GOOGLE_APPLICATION_LANGUAGE: en-AU
    volumes:
      # dev mount src
      - ./hermod-python/src:/app/src  
   
      # access to pulse audio cookie from the host
      - ${HOME}/.config/pulse/cookie:/tmp/cookie 
   
      # if not using pulse, you need to set environment variables MICROPHONE_DEVICE and SPEAKER_DEVICE
      # and uncomment the following
      # - /dev/snd:/dev/snd 
      
# hermod web server
  hermodweb:
    image: syntithenai/hermod-python
    build: ./hermod-python/
    container_name: hermodweb
    entrypoint: ['python','/app/src/services.py','-ss','-w','-r','http://rasa:5005']
    ports:
      - 80:80
    environment:
      MQTT_SERVER: mqtt
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      # enable SSL for Flask (not useful in combination with nginx-proxy)
      # SSL_CERTIFICATES_FOLDER: /app/certs
    volumes:
      # volume mount certificates folder
      #- /etc/letsencrypt/live/peppertrees.asuscomm.com:/app/certs
      # dev mount src
      - ./hermod-python/src:/app/src  
      - ./hermod-python/www:/app/www  
      # allow web service to updated mosquitto passwords
      - ./hermod-python/mosquitto:/etc/mosquitto 
# rasa
  rasa:
    image: syntithenai/hermod-python
    build: ./hermod-python/
    container_name: rasa
    entrypoint: ['python','/app/src/services.py','-ss']
    environment:
      DUCKLING_URL: http://duckling:5005
    volumes:
      - ./hermod-python/src:/app/src 
      - ./hermod-python/rasa:/app/rasa  
    #ports:
    #  - 5005
      
# rasa action server
  rasa_actions:
    image: syntithenai/hermod-python
    build: ./hermod-python
    container_name: rasa_actions
    entrypoint: ['python','/app/src/services.py','-ss','-a','-r','default']
    environment:
      MQTT_SERVER: mqtt
    volumes:
      - ./hermod-python/src:/app/src 
      - ./hermod-python/rasa:/app/rasa  
      
    #ports:
    # - 5055  

  #nginxproxy:
    #image: jwilder/nginx-proxy
    #container_name: nginx-proxy
    #restart: always
    #ports:
      #- "80:80"
      #- "443:443"
    #labels:
      #- com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    #volumes:
      #- /var/run/docker.sock:/tmp/docker.sock:ro
      #- /etc/nginxcerts:/etc/nginx/certs
      #- /var/docker/nginxproxy/vhosts:/etc/nginx/vhost.d
      #- /var/www:/usr/share/nginx/html
      #- ./nginx.tmpl:/app/nginx.tmpl
      #- /var/docker/htpasswd:/etc/nginx/htpasswd
    #environment:
     #HTTPS_METHOD: noredirect
     #DEFAULT_HOST: peppertrees.asuscomm.com
     
  #nginxproxysslgen:
    ##image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
    #image: jrcs/letsencrypt-nginx-proxy-companion:latest
    #container_name: nginxproxysslgen
    #restart: always
    #volumes_from:
      #- nginxproxy
    #volumes:
      #- /var/run/docker.sock:/var/run/docker.sock:ro
      #- /etc/nginxcerts:/etc/nginx/certs
      #- /var/docker/nginxproxy/vhosts:/etc/nginx/vhost.d
      #- /var/www:/usr/share/nginx/html


    ## ===========================================================================================   
    ## HERMOD VOICE SERVICES SUITE
    ## ===========================================================================================   
  
  #hermod:
        ##build: ./
        #image: syntithenai/hermod
        #restart: always
        ##privileged: true
        #entrypoint: "/usr/src/app/hermod-nodejs/pm2start.sh"
        #environment:
          ##PULSE_SERVER: 192.168.1.200
          ##PULSE_COOKIE: /tmp/cookie
        #ports:
           ## web
          ##- "80:80"
          ##- "443:443"
          ## mqtt 
          #- "1883:1883"
          ## mqtt web sockets 
          #- "9001:9001"
        ## on your linux desktop install paprefs and enable network access to local sound devices 
        ## update IP below to your machine
        #volumes:
            ## without pulseaudio, just allow access to sound device
            #- /dev/snd:/dev/snd
            ## HOST MOUNTS FOR DEVELOPMENT
            #- ./hermod-nodejs:/usr/src/app/hermod-nodejs
            ## ATTACH DEEPSPEECH MODEL
            #- ./deepspeech-model:/usr/src/app/hermod-nodejs/deepspeech-model
            ##- ./hermod-react-satellite:/usr/src/app/hermod-react-satellite
            ##- ./browser-example:/usr/src/app/browser-example
            ## Use PULSE
            ##- ./pulseaudio/asound-pulse.conf:/etc/asound.conf
            ##- ./pulseaudio/client.conf:/etc/pulse/client.conf
            ## PULSE COOKIE FROM HOST
            ##- /home/stever/.config/pulse/cookie:/tmp/cookie
    
