mqtt_hostname: "127.0.0.1"
mqtt_port: 1883
mqtt_protocol: "311"
services:
  AudioService:
    site: jest
    inputdevice: "pulse"
    outputdevice: "pulse"
  DeepspeechAsrService:
    model_path: "./deepspeech-models"
    vad_sensitivity: 0
  PicovoiceHotwordService:
    hotwords: "picovoice,bumblebee,porcupine"
    sensitivity: 0.5
  Pico2wavTtsService:
    binary_path: /usr/bin/pico2wave
    cache_path: /tmp/
  RasaService:
    rasa_server: "http://localhost:5005/"
  DialogManagerService:  
