mqtt_hostname: "127.0.0.1"
mqtt_port: 1883
mqtt_protocol: "311"
site: jest
services:
  MicrophoneService:
  SpeakerService:
  #deepspeech_asr_service:
  DeepspeechAsrService:
    model_path: "./deepspeech-models"
    vad_sensitivity: 2
  PicovoiceHotwordService:
    hotwords: "picovoice,bumblebee,porcupine"
    sensitivity: 0.5
  Pico2wavTtsService:
    binary_path: /usr/bin/pico2wave
    cache_path: /tmp/
  DialogManagerService:
  RasaNluService:
    model_path: "./rasa/models/nlu"
  
